### ISSUE TITLE
How to process Wikibio data?

### ISSUE THREAD

**Issue by Tiiiger** [swiseman/neighbor-splicing#1]
Hi @swiseman ,

Thank you for releasing the code for your awesome paper! I just want to ask if you can help release to code the process Wikibio into the data format you are using?

Thank you in advance!

**Comment by swiseman** [comment]
Hello, thanks for your interest! Yes, I just updated the README to add instructions for processing the WikiBio data, and also a [link](https://drive.google.com/drive/folders/1xtO5_yyjZWOLHcY5Wyr6fIUZrC1bq0BV?usp=sharing) where the preprocessed files can be downloaded. Let me know if you need anything else.

**Comment by Tiiiger** [comment]
Lovely. Thank you!
