### ISSUE TITLE
My training process always output assuming OOM

### ISSUE THREAD

**Issue by happycjksh** [swiseman/neighbor-splicing#2]
![54F09659C47D833F4BCF1EC655D21959](https://user-images.githubusercontent.com/59444174/147389249-a0a0dbc7-7cd1-466c-abab-70c75b7bb5ef.png)
I don't know why. I have stuck in the step for two days. Could you help me?

**Comment by swiseman** [comment]
If you look at the code (https://github.com/swiseman/neighbor-splicing/blob/main/train.py#L105) you'll see it's just catching any RuntimeError and assuming it's an out of memory issue. You can re-raise the error (as in the previous commented-out line) to check what is actually happening.

**Comment by happycjksh** [comment]
I found that the pytorch not match with the cuda, such that I have to use cpu
