### ISSUE TITLE
I have the error: index 250 is out of bounds for dimension 0 with size 250

### ISSUE THREAD

**Issue by happycjksh** [swiseman/neighbor-splicing#3]
![9BAE08D73F12D9F2EF79DFD3CBAB0516](https://user-images.githubusercontent.com/59444174/147411564-a03189d2-6e25-40c6-9898-758407bba92e.png)
![8EABF4A0382477A7C8452F4F6BF41AE3](https://user-images.githubusercontent.com/59444174/147411662-73887c8b-3bdd-4e6d-9411-2135d0beae50.png)
When I train the model, the code occurs the error. I print the key values and I found that the when the bsz=261, the index is out of range. However, when I set the slide always equal to 261, the length equal to 250.  
I don't know why the same values can output two different results. Could you help me solve the problem?
Thank you very much

**Comment by swiseman** [comment]
That mask is initialized [here](https://github.com/swiseman/neighbor-splicing/blob/main/train.py#L310) with a first dimension size (`max_ncanvs`) of 250, which is supposed to be an upper bound on the total number of canvases you'd have cumulatively in any minibatch. `max_ncanvs` is set hackily in this way rather than finding the true maximum cumulative number of canvases per batch to avoid having to run through all the batches before starting training. So the simplest way to fix this error is just to increase `max_ncanvs` to something bigger (e.g., 300). I don't understand what you mean by setting the slide, but your code trace looks reasonable to me other than this indexing issue.

**Comment by happycjksh** [comment]
when I run your code, the index error will occur, so I write the trace code. I found that in the training process, the bsz will automatically equal to 261, but the endmask equal to 250. In other cases, the bsz is always equaling to the endmask's length. I guess that the 261 larger than 250 leads the index error, but when I print the len(e = e[:261, :canvases.size(0), :remembes.size(0)]), I found the length is 250, not 261. I don't know what leads the result.

**Comment by swiseman** [comment]
Yes, it is expected that if you over-index you will just get the true length of the tensor, which is always at most `max_ncanvs`. The fix for now is just to increase `max_ncanvs`, but I'll try to implement a more elegant fix soon.

**Comment by happycjksh** [comment]
Thank you for your replying. I will try to solve it today. I'll tell you the result in this night

**Comment by happycjksh** [comment]
I solve it by setting the max_ncanvs equal to 400, but I don't know whether the changing influences the reproduce.

**Comment by happycjksh** [comment]
Hello, thank you for your sharing. Through following your tips, I have obtained the generated texts. However, you don't tell me how to calculate the metrics through your open source code. I need write the calculation code by myself?

**Comment by swiseman** [comment]
For E2E you can use the scripts in the E2E metrics [repo](https://github.com/tuetschek/e2e-metrics). For WikiBio it's probably easiest to use something like [files2rouge](https://github.com/pltrdy/files2rouge) with arguments `-a "-c 95 -r 1000 -n 4 -a"`.

**Comment by happycjksh** [comment]
Hello, I can't reproduce the result. I don't know where I make the mistakes. First, I generate the e2e_val.out. Then, I convert the file into the .txt format. Finally, I  run the measure_score.py, but I can't reproduce the result. I want to know whether I have somewhere occurs error. Thank you for your reply.

**Comment by swiseman** [comment]
The output file generated by `search.py` contains a bunch of extra meta-data that needs to be stripped before evaluation. I just uploaded a [script](https://github.com/swiseman/neighbor-splicing/blob/main/eval_e2e_out.bash) that does this and then calls the E2E evaluation code. It should be run like `bash eval_e2e_out.bash e2e.out target_file.txt` (e.g., for the test data, run `bash eval_e2e_out.bash e2e.out data/e2e/test-conc.txt`). This bash script relies on a detokenization [script](https://github.com/UFAL-DSG/tgen/blob/master/e2e-challenge/postprocess/postprocess.py) in the TGen [repo](https://github.com/UFAL-DSG/tgen). I'll update the README with this. I was able to retrain from scratch and get numbers very close to those in the paper. It looks like using a slightly bigger beam (e.g., `-K 10`) gives results even better than those in the paper.

**Comment by happycjksh** [comment]
Hello, I still con't reproduce the result. I follow your tips generate a clean text file. Then I generate a gold text file, the format is .json. Finally, I load the two files to calculate the Bleu, but I can reproduce the result which you record in the paper. The reason that I don't bash eval_e2e_out.bash is that I don't find the src_uniq_valid.txt corresponding gold_target_file.txt, such that I generate a gold_target_file.txt by myself. The final BLEU is 45.2. I don't know where I occur errors.

**Comment by happycjksh** [comment]
I have reproduced the result. Thank you very much

**Comment by swiseman** [comment]
Great! I'm going to close the issue.
